### ISSUE TITLE
Add a ExpandOnClick property, or remove the default expand-on-click behavior

### ISSUE THREAD

**Issue by ramduq** [excubo-ag/Blazor.TreeViews#45]
When clicking on a tree node, it expanses/collapses. This might not be a desirable behavior in all cases. Please add a property `ExpandOnClick`, so this behavior can be overridden.

Some context:
I'm using the tree with single-selection (implemented with an `ItemTemplate` containing a link with an `@onclick` event). When a node is clicked then, on the right side of the page, the details of the selected item are loaded. So, a user clicks on a node and expects to just select it (the expand/collapse behavior is perceived as a bug).

I tried to handle this by adding `@onclick:stopPropagation="true"` to the link. However, any click outside the bounds of the link still expands/collapses the node.

**Comment by stefanloerwald** [comment]
`@onclick:stopPropagation="true"` is the intended solution here. I realized that the ItemTemplate could not be sized approriately due to the surrounding elements. 

Please update to version 3.3.0. Then, you're free to expand the outermost element of your ItemTemplate to take full width (`style="width: 100%"`) and stop propagation, which should make the entire element not react to clicks.
